version: '2'

services:
  sogo:
    build: .
    container_name: sogo
    ports:
    - 20000:20000
    environment:
    - MYSQL_SERVER=mariadb
    - MYSQL_ROOT_PASSWORD=test
    - MYSQL_USER=sogo
    - MYSQL_USER_PASSWORD=sogoPassword
    - MYSQL_DATABASE_NAME=sogo
    - SOGO_SOGoIMAPServer="imaps://imap.server.com:143/?tls=yes"
    - SOGO_SOGoSMTPServer=smtp.server.com
    - SOGO_SOGoMailDomain=server.com
    - SOGO_SOGoMailingMechanism=smtp
    - SOGO_SOGoSMTPAuthenticationType=PLAIN
    - SOGO_SOGoForceExternalLoginWithEmail=YES
    - SOGO_NGImap4ConnectionStringSeparator="."
    - SOGO_SOGoPasswordChangeEnabled=NO
    - SOGO_SOGoForwardEnabled=YES
    - SOGO_SOGoSieveScriptsEnabled=YES
    - SOGO_SOGoTimeZone=Europe/Paris
    - SOGO_WorkersCount=4
    - SOGO_SOGoCalendarDefaultRoles=("PublicDAndTViewer","ConfidentialDAndTViewer","PrivateDAndTViewer")
    - SOGO_SOGoUserSources=({
          canAuthenticate = YES;
          displayName = "SOGo Users";
          id = users; isAddressBook = YES;
          type = sql;
          userPasswordAlgorithm = md5;
          viewURL ="mysql://sogo:sogoPassword@mariadb:3306/sogo/sogo_users";
          KindFieldName = kind;
          MultipleBookingsFieldName = multiple_bookings;
      })

  nginx:
    image: nginx
    container_name: nginx
    links:
    - sogo
    volumes_from:
    - sogo:ro
    ports:
    - 80:80
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro

  mariadb:
    image: mariadb:10.1
    container_name: mariadb
    environment:
    - MYSQL_ROOT_PASSWORD=test
    ports:
    - 3306:3306
    volumes:
    - "./data:/var/lib/mysql"